---
- name: Install python boto module
  become: yes
  apt:
    name: python-boto
    state: present

- name: Set app name env variable
  become: yes
  shell: "bash -c 'echo \"APP_NAME={{ app_name }}\" >> /etc/environment'"

- name: Set app version env variable
  become: yes
  shell: "bash -c 'echo \"APP_VERSION={{ app_version }}\" >> /etc/environment'"

- name: Create download and unpack directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ download_dir }}"
    - "{{ unpack_dir }}"

- name: Retrieve deployment package
  s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ package }}"
    dest: "{{ download_dir }}/{{ package }}"
    mode: get
    overwrite: no

- name: Unpack package
  unarchive:
    copy: no
    src: "{{ download_dir }}/{{ package }}"
    dest: "{{ unpack_dir }}"
    extra_opts: "deploy/scripts"
  notify:
    - install app
    - restart app



