---
- name: Install python boto module
  become: yes
  apt:
    name: python-boto
    state: present

- name: Create download and unpack directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ download_dir }}"
    - "{{ unpack_dir }}"

- name: Retrieve deployment package
  s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ package }}"
    dest: "{{ download_dir }}/{{ package }}"
    mode: get

- name: Unpack package
  unarchive:
    copy: no
    src: "{{ download_dir }}/{{ package }}"
    dest: "{{ unpack_dir }}"
    extra_opts: "deploy/scripts"

- name: Install app
  become: yes
  shell: "bash -c \"{{ unpack_dir }}/deploy/scripts/install_upstart_server.sh {{ download_dir}}/{{ package }} &> /var/log/surfspotter.install.log\""
  notify: "restart {{ app_name }}"


