---
- name: gather subnet facts
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      default-for-az: "true"
      availability-zone: "{{ region }}a"
  register: subnet_facts

- name: Create EC2
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    instance_type: t2.micro
    image: ami-ed82e39e
    vpc_subnet_id: "{{ subnet_facts.subnets[0].id }}"
    group_id: "{{ sg.group_id }}"
    assign_public_ip: yes
    instance_tags: { "Name":"{{ app_name }}_ec2" }
