---
- name: gather subnet facts
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      default-for-az: "true"
      availability-zone: "{{ region }}{{ availability_zone }}"
  register: subnet_facts

- name: Create EC2
  ec2:
    key_name: "{{ ssh_key_name }}"
    region: "{{ region }}"
    zone: "{{ region }}{{ availability_zone }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ subnet_facts.subnets[0].id }}"
    group_id: "{{ sg.group_id }}"
    instance_profile_name: "{{ app_name }}_iam_role"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ app_name }}_ec2"
      Version: "{{ app_version }}"
    count_tag:
      Name: "{{ app_name }}_ec2"
      Version: "{{ app_version }}"
    exact_count: 2
    wait: true
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"




